### ISSUE TITLE
Suggestion: Cache search results

### ISSUE THREAD

**Issue by mickdekkers** [tenorz007/cerebro-github#1]
Right now they are not cached, causing the plugin to keep sending requests for the same input until it hits the rate limit and a repository search error is displayed.
You can reproduce this by searching for anything and pressing the up/down arrows to scroll to the GitHub entry, then keep pressing up/down (or mouse over/away) to reload the results.

**Comment by tenorz007** [comment]
I had initially planned to implement the caching at a single entry point but then I trending today results could change and that would then lead to wrong results (not by much) and I never did experience the rate limit so I had felt it was fine. However can you show me what exactly you searched for, cause I doubt there's rate limiting on the 'github.com'

**Comment by mickdekkers** [comment]
Sure, it happens with any query but I tried it with "express".

**Comment by tenorz007** [comment]
Thanks for pointing it out to me, I hadn't experienced it so I thought I'd get away with that. I'll add caching.

**Comment by tenorz007** [comment]
I have added caching to the new release. I'll be closing this issue as a result, feel free to reopen if you feel it hasn't been resolved
